export enum ActionType{
  APPLIED_FOR_PROJECT = "APPLIED_FOR_PROJECT",
  PROJECT_ASSIGNED = "PROJECT_ASSIGNED",
  PROPOSAL_SUBMITTED = "PROPOSAL_SUBMITTED",
  PROJECT_CREATED = "PROJECT_CREATED",
  PROPOSAL_ACCEPTED = "PROPOSAL_ACCEPTED",
  PROPOSAL_REJECTED = "PROPOSAL_REJECTED",
  PROPOSAL_WITHDRAWN = "PROPOSAL_WITHDRAWN"
}