export enum ChoiceStatus {
    APPLIED = 'APPLIED',
    UNDER_REVIEW = 'UNDER_REVIEW',
    SHORTLISTED = 'SHORTLISTED',
    ALLOCATED = 'ALLOCATED',
    NOT_SELECTED = 'NOT_SELECTED',
    WITHDRAWN = 'WITHDRAWN'
  }